# This is a basic workflow to help you get started with Actions

name: self-hosted

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#      - name: create secrets
#        run: |
#          ls
#          cp ../../../secrets/key.properties ./android/
#          cp ../../../secrets/local.properties ./android/
#          cp ../../../secrets/pomodash.jks ./android/app/
#          cp ../../../secrets/google-services-prod.json ./android/app/src/prod/google-services.json
#          cp ../../../secrets/google-services-dev.json ./android/app/src/dev/google-services.json

      # Runs a set of commands using the runners shell
      - name: flutter test
        run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/apk/prod/release/app-prod-release.apk